// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface StorageSlot$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "StorageSlot",
  "sourceName": "@openzeppelin/contracts/utils/StorageSlot.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220bcb9c3a5360c13b0ac8c62d207560b0e1e6ba4c48b9c8ba8bc8f8c98f6f0cebb64736f6c634300081b0033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220bcb9c3a5360c13b0ac8c62d207560b0e1e6ba4c48b9c8ba8bc8f8c98f6f0cebb64736f6c634300081b0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<StorageSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/StorageSlot.sol:StorageSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<StorageSlot$Type["abi"]>>;
}
