// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SnapArcMarket$Type } from "./SnapArcMarket";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SnapArcMarket"]: SnapArcMarket$Type;
    ["contracts/SnapArcMarket.sol:SnapArcMarket"]: SnapArcMarket$Type;
  }

  interface ContractTypesMap {
    ["SnapArcMarket"]: GetContractReturnType<SnapArcMarket$Type["abi"]>;
    ["contracts/SnapArcMarket.sol:SnapArcMarket"]: GetContractReturnType<SnapArcMarket$Type["abi"]>;
  }
}
